# Options relating to the general operation of the plugin.
General:
    # Whether or not to use the "secure" method of changing blocks. The "secure" method is recommended but slightly slower.
    # The secure method forces the original block to be broken and a replacement block to be inserted in its place.
    # If this is turned off, the block will simply have its type changed and will not offer any security in protected regions.
    Secure: true

# Options relating to dying blocks.
Dye:
    # Whether or not to consume a dye when it is used.
    Consume: true
    
# Options relating to the economy.
Economy:
    # Enable the economy system (dying blocks will be charged).
    Enabled: false
    # The economy adapter to use (iConomy or MineConomy).
    Adapter: iConomy
    # The cost to dye a block.
    DyeCost: 1
    
# Options relating to colour fill.
Fill:
    # The maximum number of blocks to change when performing a fill.
    Max: 1000
    # Whether or not to charge per block (if the economy system is enabled).
    ChargePerBlock: true

# Options relating to change history.
History:
    # Whether or not to enable history.
    Enabled: true
    # The maximum number of block changes to keep in history per-player (fills count as one change).
    Max: 10
    # Whether or not to refund the player when undoing changes.
    RefundOnRollback: true
    # Whether or not to persist undo history after the player logs off (not recommended).
    PersistOnLogout: false

# Options relating to transmutation (changing non-wool blocks into coloured-wool blocks).
Transmutation:
    # Whether or not to enable fill transmutation (it's highly recommended that this is false).
    EnableFill: false
    # A list of blocks that can be transmuted, and their costs.
    Blocks:
        STONE: 1
        COBBLESTONE: 1