name: Flexiwool
main: me.ryall.flexiwool.Flexiwool
version: 1.2.0
description: Make your world a more colourful place with lots of control over wool and wool colours.
author: SirHedgehog
commands:
    flexiwool:
        description: Flexiwool command
        usage: /flexiwool <command> <params>
    fw:
        description: Flexiwool command shorthand
        usage: /fw <command> <params>