name: Painter
main: me.ryall.painter.Painter
version: 1.2.1
description: Make your world a more colourful place with lots of control over wool and wool colours.
author: SirHedgehog
commands:
    painter:
        description: Painter command
        usage: /paint <command> [params]
    paint:
        description: Painter command shorthand
        usage: /paint <command> [params]